name: Publish Travel Planner

on:
  workflow_dispatch:
  push:
    branches:
    - master
env:
  AZURE_WEBAPP_NAME: Travel-Planner-web-app

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
         dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ./Travel-Planner.API/Travel-Planner.API.csproj

      - name: Build
        run: dotnet build ./Travel-Planner.API/Travel-Planner.API.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./Travel-Planner.API/Travel-Planner.API.csproj --configuration Release --no-build

        #deploy on azure
      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.API_PUBLISH_SECRET }}
          package: ./publish
